app/models/user.py
from flask_login import UserMixin
from app import sql


class User(sql.Model, UserMixin):
    __tablename__ = 'user'
    id = sql.Column(sql.Integer, primary_key=True)
    username = sql.Column(sql.String(120), unique=True, nullable=False)
    email = sql.Column(sql.String(120), unique=True, nullable=False)
    password = sql.Column(sql.String(120), nullable=False)
    role = sql.Column(sql.String(6), nullable=False, default='Reader')
    date_created = sql.Column(sql.DateTime, default=sql.func.current_timestamp())
    date_modified = sql.Column(
        sql.DateTime, default=sql.func.current_timestamp(),
        onupdate=sql.func.current_timestamp()
    )

app/routes/users.py
from flask import Blueprint, render_template, request, redirect, url_for
from flask_injector import inject
from flask_login import login_required

from app.decorators import role_required
from app.forms.users.role import UpdateUserRoleForm
from app.services.user import UserService

users = Blueprint("users", __name__)


@users.route('/', methods=['GET'])
@login_required
@role_required(['Admin'])
@inject
def list_all(user_service: UserService):
    all_users = user_service.get_all()
    user_forms = {}
    for user in all_users:
        form = UpdateUserRoleForm(obj=user)
        form.user_id.data = user.id
        user_forms[user.id] = form
    return render_template('users/users_list.html', users=all_users, form=user_forms)


@users.route('/update', methods=['POST'])
@login_required
@role_required(['Admin'])
@inject
def update(user_service: UserService):
    form = UpdateUserRoleForm(request.form)
    if form.validate_on_submit():
        user_id = form.user_id.data
        role = form.role.data
        user_service.update(user_id, role)
    return redirect(url_for('users.list_all'))

app/templates/users/users_list.html
{% extends "layout.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block page_title %} Users List {% endblock %}

{% block container %}
    <div class="container mt-4">
        <h1 class="mb-4">Users List</h1>

        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th>ID</th>
                <th>Username</th>
                <th>Email</th>
                <th>Role</th>
                <th>Update Role</th>
            </tr>
            </thead>
            <tbody>
            {% for user in users %}
                <tr>
                    <td>{{ user.id }}</td>
                    <td>{{ user.username }}</td>
                    <td>{{ user.email }}</td>
                    <td>{{ user.role }}</td>
                    <td>
                        <form method="POST" action="{{ url_for('users.update') }}">
                            {{ form[user.id].hidden_tag() }}
                            <div class="form-group table">
                                {{ wtf.form_field(form[user.id].user_id, class="form-control") }}
                                {{ wtf.form_field(form[user.id].role, class="form-control") }}
                                {{ wtf.form_field(form[user.id].submit, class="btn btn-primary ml-2") }}
                            </div>
                        </form>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}