app/models/post.py
from sqlalchemy.orm import backref

from app import sql


class Post(sql.Model):
    __tablename__ = 'post'
    id = sql.Column(sql.Integer, primary_key=True)
    author_id = sql.Column(sql.Integer, sql.ForeignKey('user.id'), nullable=False)
    title = sql.Column(sql.String(120), nullable=False)
    content = sql.Column(sql.String(120), nullable=False)
    date_created = sql.Column(sql.DateTime, default=sql.func.current_timestamp())
    date_modified = sql.Column(
        sql.DateTime, default=sql.func.current_timestamp(),
        onupdate=sql.func.current_timestamp()
    )
    author = sql.relationship('User', backref=backref('posts'), lazy=True)

app/routes/posts.py
from flask import Blueprint, render_template, url_for, redirect, request
from flask_login import login_required, current_user
from injector import inject

from app.decorators import role_required
from app.forms.posts.create_edit_form import CreateEditPostForm
from app.forms.posts.delete_form import DeletePostForm
from app.services.post import PostService
from app.services.user import UserService

posts = Blueprint("posts", __name__)


@posts.route('/', methods=['GET', 'POST'])
@login_required
@inject
def list_all(post_service: PostService, user_service: UserService):
    delete_post_form = DeletePostForm()
    all_posts = post_service.get_all()
    likes = post_service.get_likes(1)
    dislikes = post_service.get_dislikes(1)
    for post in all_posts:
        post.author = user_service.get_by_id(post.author_id)
        post.author_username = post.author.username
        post.author_id = int(post.author_id)
        post.likes = post_service.get_likes(post.id)
        post.dislikes = post_service.get_dislikes(post.id)
    return render_template('posts/posts_list.html', posts=all_posts, form=delete_post_form)


@posts.route('/myposts', methods=['GET', 'POST'])
@login_required
@inject
def list_author_posts(post_service: PostService, user_service: UserService):
    delete_post_form = DeletePostForm()
    author_id = current_user.id
    author_posts = post_service.get_all_by_author_id(author_id)
    for post in author_posts:
        post.author = user_service.get_by_id(post.author_id)
        post.author_username = post.author.username
        post.author_id = int(post.author_id)
        post.likes = post_service.get_likes(post.id)
        post.dislikes = post_service.get_dislikes(post.id)
    return render_template('posts/my_posts.html', posts=author_posts, form=delete_post_form)


@posts.route('/<int:post_id>', methods=['GET'])
@login_required
@inject
def view(post_service: PostService, user_service: UserService, post_id):
    delete_post_form = DeletePostForm()
    post = post_service.get_by_id(post_id)
    author_username = user_service.get_by_id(post.author_id).username
    post.author_username = author_username
    post.likes = post_service.get_likes(post.id)
    post.dislikes = post_service.get_dislikes(post.id)
    post.liked = post_service.is_liked_by_user(post.id)
    post.disliked = post_service.is_disliked_by_user(post.id)
    return render_template('posts/view_post.html', post=post, form=delete_post_form)


@posts.route('/create', methods=['POST', 'GET'])
@login_required
@role_required(['Admin', 'Author'])
@inject
def create(post_service: PostService):
    create_post_form = CreateEditPostForm()
    if create_post_form.validate_on_submit():
        post_service.create(create_post_form.title.data, create_post_form.content.data, current_user.id)
        return redirect(url_for('posts.list_author_posts'))
    return render_template('posts/create_post.html', form=create_post_form)


@posts.route('/<post_id>/edit', methods=['GET', 'POST'])
@login_required
@role_required(['Admin', 'Author'])
@inject
def edit(post_service: PostService, post_id):
    post = post_service.get_by_id(post_id)
    edit_post_form = CreateEditPostForm(obj=post)
    if edit_post_form.validate_on_submit():
        post_service.update(post_id, edit_post_form.title.data, edit_post_form.content.data)
        return redirect(url_for('posts.view', post_id=post_id))
    return render_template('posts/edit_post.html', form=edit_post_form, post_id=post_id)


@posts.route('/<int:post_id>/delete', methods=['POST'])
@login_required
@role_required(['Admin', 'Author'])
@inject
def delete(post_service: PostService, post_id):
    post_service.delete(post_id)
    return redirect(request.referrer)


@posts.route('/<int:post_id>/like', methods=['POST'])
@login_required
@inject
def like(post_service: PostService, post_id):
    post_service.like(post_id)
    return redirect(request.referrer)


@posts.route('/<int:post_id>/dislike', methods=['POST'])
@login_required
@inject
def dislike(post_service: PostService, post_id):
    post_service.dislike(post_id)
    return redirect(request.referrer)

app/templates/posts/create_post.html
{% extends "layout.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block page_title %} Add Blog Post {% endblock %}

{% block container %}
    <div class="container">
        <h1>Create a new post</h1>
        <form method="post" action="{{ url_for('posts.create') }}">
            {{ form.hidden_tag() }}

            {{ wtf.form_field(form.title) }}
            {{ wtf.form_field(form.content) }}
            <button type="submit" class="btn btn-secondary mr-5">Create Post</button>
        </form>
    </div>
{% endblock %}

app/templates/posts/edit_post.html
{% extends "layout.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block page_title %} Edit Blog Post {% endblock %}

{% block container %}
    <div class="container">
        <h1>Edit Post</h1>
        <form method="post" action="{{ url_for('posts.edit', post_id=post_id) }}">
            {{ form.hidden_tag() }}
            {{ wtf.form_field(form.title) }}
            {{ wtf.form_field(form.content) }}
            <button type="submit" class="btn btn-secondary mr-5">Edit Post</button>
        </form>
    </div>
{% endblock %}

app/templates/posts/my_posts.html
{% extends "layout.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block page_title %} {{ post_title }} {% endblock %}

{% block container %}
    <div class="container mt-4">
        <h1> My Posts </h1>
        {% if posts %}
            <div class="list-group">
                {% for post in posts %}
                    <div class="list-group-item mb-3 post-box">
                        <h5 class="mb-1">{{ post.title }}</h5>
                        <small>@{{ post.author_username }} - {{ post.date_created.strftime('%Y-%m-%d %H:%M') }}</small>
                        <div class="mt-2">
                            <span class="badge badge-primary">Likes: {{ post.likes }}</span>
                            <span class="badge badge-secondary">Dislikes: {{ post.dislikes }}</span>
                        </div>
                        <div class="post-buttons mt-2">
                            <a href="{{ url_for('posts.view', post_id=post.id) }}" class="btn btn-info btn-sm">View</a>
                            {% if current_user.is_authenticated %}
                                {% if 'Admin' in current_user.role or post.author_id == current_user.id %}
                                    <a href="{{ url_for('posts.edit', post_id=post.id) }}"
                                       class="btn btn-warning btn-sm"
                                       title="Edit this post">Edit</a>
                                    <form action="{{ url_for('posts.delete', post_id=post.id) }}" method="POST"
                                          style="display:inline;">
                                        {{ form.hidden_tag() }}
                                        <input type="hidden" name="_method" value="DELETE">
                                        <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                    </form>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>No posts available.</p>
        {% endif %}
    </div>
{% endblock %}

app/templates/posts/posts_list.html
{% extends "layout.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block page_title %} {{ post_title }} {% endblock %}

{% block container %}
    <div class="container mt-4">
        <h1> All Posts </h1>
        {% if posts %}
            <div class="list-group">
                {% for post in posts %}
                    <div class="list-group-item mb-3 post-box">
                        <h5 class="mb-1">{{ post.title }}</h5>
                        <small>@{{ post.author_username }} - {{ post.date_created.strftime('%Y-%m-%d %H:%M') }}</small>
                        <div class="mt-2">
                            <span class="badge badge-primary">Likes: {{ post.likes }}</span>
                            <span class="badge badge-secondary">Dislikes: {{ post.dislikes }}</span>
                        </div>
                        <div class="post-buttons mt-2">
                            <a href="{{ url_for('posts.view', post_id=post.id) }}" class="btn btn-info btn-sm">View</a>
                            {% if current_user.is_authenticated %}
                                {% if 'Admin' in current_user.role or post.author_id == current_user.id %}
                                    <a href="{{ url_for('posts.edit', post_id=post.id) }}"
                                       class="btn btn-warning btn-sm"
                                       title="Edit this post">Edit</a>
                                    <form action="{{ url_for('posts.delete', post_id=post.id) }}" method="POST"
                                          style="display:inline;">
                                        {{ form.hidden_tag() }}
                                        <input type="hidden" name="_method" value="DELETE">
                                        <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                                    </form>
                                {% endif %}
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
            </div>
        {% else %}
            <p>No posts available.</p>
        {% endif %}
    </div>
{% endblock %}

app/templates/posts/view_post.html
{% extends "layout.html" %}

{% import "bootstrap/wtf.html" as wtf %}

{% block page_title %} {{ post.title }} {% endblock %}

{% block container %}

    <div class="container mt-4">
        <h1>{{ post.title }}</h1>
        <small>@{{ post.author_username }} - {{ post.date_created.strftime('%Y-%m-%d %H:%M') }}</small>
        <div class="mt-2">
            <span class="badge badge-primary">Likes: {{ post.likes }}</span>
            <span class="badge badge-secondary">Dislikes: {{ post.dislikes }}</span>
        </div>
        <div class="post-content mt-4" style="word-wrap: break-word; overflow-wrap: break-word;">
            <p>{{ post.content }}</p>
        </div>

        <div class="post-buttons mt-4">
            {% if current_user.is_authenticated %}
                {% if 'Admin' in current_user.role or post.author_id == current_user.id %}
                    <a href="{{ url_for('posts.edit', post_id=post.id) }}" class="btn btn-warning btn-sm">Edit</a>
                    <form action="{{ url_for('posts.delete', post_id=post.id) }}" method="POST"
                          style="display:inline;">
                        {{ form.hidden_tag() }}
                        <input type="hidden" name="_method" value="DELETE">
                        <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                    </form>
                {% endif %}
            {% endif %}
        </div>
        <div class="mt-4">
            {% if post.liked %}
                <form action="{{ url_for('posts.like', post_id=post.id) }}" method="POST"
                      style="margin-right: 10px;">
                    {{ form.hidden_tag() }}
                    <button type="submit" class="btn btn-primary btn-sm">Liked</button>
                </form>
            {% else %}
                <form action="{{ url_for('posts.like', post_id=post.id) }}" method="POST"
                      style="margin-right: 10px;">
                    {{ form.hidden_tag() }}
                    <button type="submit" class="btn btn-primary btn-sm">Like</button>
                </form>
            {% endif %}

            {% if post.disliked %}
                <form action="{{ url_for('posts.dislike', post_id=post.id) }}" method="POST">
                    {{ form.hidden_tag() }}
                    <button type="submit" class="btn btn-secondary btn-sm">Disliked</button>
                </form>
            {% else %}
                <form action="{{ url_for('posts.dislike', post_id=post.id) }}" method="POST">
                    {{ form.hidden_tag() }}
                    <button type="submit" class="btn btn-secondary btn-sm">Dislike</button>
                </form>
            {% endif %}
        </div>
    </div>
{% endblock %}