app/routes/auth.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_injector import inject
from flask_login import login_required
from app.services.user import UserService
from app.forms.auth.login import LoginForm
from app.forms.auth.signup import SignupForm

auth = Blueprint("auth", __name__)


@auth.route('/login', methods=['GET', 'POST'])
@inject
def login(user_service: UserService):
    login_form = LoginForm()
    if login_form.validate_on_submit():
        if user_service.login(login_form.username.data, login_form.password.data):
            return redirect(url_for('dashboard.home'))
        else:
            flash("Invalid username or password", "danger")
    return render_template('auth/login.html', form=login_form)


@auth.route('/signup', methods=['GET', 'POST'])
@inject
def signup(user_service: UserService):
    signup_form = SignupForm()
    if signup_form.validate_on_submit():
        if not user_service.get_by_username(username=signup_form.username.data) and not user_service.get_by_email(
                email=signup_form.email.data):
            user_service.signup(
                signup_form.username.data,
                signup_form.email.data,
                signup_form.password.data
            )
            return redirect(url_for('auth.login'))
        else:
            if user_service.get_by_username(username=signup_form.username.data) and user_service.get_by_email(
                    email=signup_form.email.data):
                flash("Username and email already exists", "danger")
            elif user_service.get_by_username(username=signup_form.username.data):
                flash("Username already exists", "danger")
            elif user_service.get_by_email(email=signup_form.email.data):
                flash("Email already exists", "danger")

    print(signup_form.errors)
    return render_template('auth/signup.html', form=signup_form)


@auth.route('/logout')
@login_required
@inject
def logout(user_service: UserService):
    user_service.logout()
    return redirect(url_for('auth.login'))

app/routes/posts.py
from flask import Blueprint, render_template, url_for, redirect, request
from flask_login import login_required, current_user
from injector import inject

from app.decorators import role_required
from app.forms.posts.create_edit_form import CreateEditPostForm
from app.forms.posts.delete_form import DeletePostForm
from app.services.post import PostService
from app.services.user import UserService

posts = Blueprint("posts", __name__)


@posts.route('/', methods=['GET', 'POST'])
@login_required
@inject
def list_all(post_service: PostService, user_service: UserService):
    delete_post_form = DeletePostForm()
    all_posts = post_service.get_all()
    likes = post_service.get_likes(1)
    dislikes = post_service.get_dislikes(1)
    for post in all_posts:
        post.author = user_service.get_by_id(post.author_id)
        post.author_username = post.author.username
        post.author_id = int(post.author_id)
        post.likes = post_service.get_likes(post.id)
        post.dislikes = post_service.get_dislikes(post.id)
    return render_template('posts/posts_list.html', posts=all_posts, form=delete_post_form)


@posts.route('/myposts', methods=['GET', 'POST'])
@login_required
@inject
def list_author_posts(post_service: PostService, user_service: UserService):
    delete_post_form = DeletePostForm()
    author_id = current_user.id
    author_posts = post_service.get_all_by_author_id(author_id)
    for post in author_posts:
        post.author = user_service.get_by_id(post.author_id)
        post.author_username = post.author.username
        post.author_id = int(post.author_id)
        post.likes = post_service.get_likes(post.id)
        post.dislikes = post_service.get_dislikes(post.id)
    return render_template('posts/my_posts.html', posts=author_posts, form=delete_post_form)


@posts.route('/<int:post_id>', methods=['GET'])
@login_required
@inject
def view(post_service: PostService, user_service: UserService, post_id):
    delete_post_form = DeletePostForm()
    post = post_service.get_by_id(post_id)
    author_username = user_service.get_by_id(post.author_id).username
    post.author_username = author_username
    post.likes = post_service.get_likes(post.id)
    post.dislikes = post_service.get_dislikes(post.id)
    post.liked = post_service.is_liked_by_user(post.id)
    post.disliked = post_service.is_disliked_by_user(post.id)
    return render_template('posts/view_post.html', post=post, form=delete_post_form)


@posts.route('/create', methods=['POST', 'GET'])
@login_required
@role_required(['Admin', 'Author'])
@inject
def create(post_service: PostService):
    create_post_form = CreateEditPostForm()
    if create_post_form.validate_on_submit():
        post_service.create(create_post_form.title.data, create_post_form.content.data, current_user.id)
        return redirect(url_for('posts.list_author_posts'))
    return render_template('posts/create_post.html', form=create_post_form)


@posts.route('/<post_id>/edit', methods=['GET', 'POST'])
@login_required
@role_required(['Admin', 'Author'])
@inject
def edit(post_service: PostService, post_id):
    post = post_service.get_by_id(post_id)
    edit_post_form = CreateEditPostForm(obj=post)
    if edit_post_form.validate_on_submit():
        post_service.update(post_id, edit_post_form.title.data, edit_post_form.content.data)
        return redirect(url_for('posts.view', post_id=post_id))
    return render_template('posts/edit_post.html', form=edit_post_form, post_id=post_id)


@posts.route('/<int:post_id>/delete', methods=['POST'])
@login_required
@role_required(['Admin', 'Author'])
@inject
def delete(post_service: PostService, post_id):
    post_service.delete(post_id)
    return redirect(request.referrer)


@posts.route('/<int:post_id>/like', methods=['POST'])
@login_required
@inject
def like(post_service: PostService, post_id):
    post_service.like(post_id)
    return redirect(request.referrer)


@posts.route('/<int:post_id>/dislike', methods=['POST'])
@login_required
@inject
def dislike(post_service: PostService, post_id):
    post_service.dislike(post_id)
    return redirect(request.referrer)

app/templates/index.html
{% extends "layout.html" %}

{% import "bootstrap/utils.html" as utils %}

{% block page_title %}Welcome{% endblock %}

{% block container %}
<div class="container mt-4">
    <div class="jumbotron text-center">
        <h1 class="display-4">Welcome to Our Blog Application!</h1>
        {% if not current_user.is_authenticated %}
        <p class="lead">Login/Signup to start blogging!</p>
        {% endif %}
    </div>
</div>
{% endblock %}

app/templates/layout.html
{% extends "bootstrap/base.html" %}

{% block html_attribs %} lang="en"{% endblock %}

{% block title %}
    {% block page_title %}{% endblock %} | Blog App
{% endblock %}

{% block metas %}
    {{ super() }}

    <meta charset="UTF-8">
    <link rel="icon" href="/favicon.ico">
{% endblock %}

{% block styles %}
    {{ super() }}

    <meta charset="UTF-8">
    <link rel="icon" href="/favicon.ico">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
{% endblock %}

{% block navbar %}
    <header class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand mr-5" href="{{ url_for('dashboard.home') }}">Blog App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav d-flex flex-row justify-content-between w-100">
                <div class="d-flex flex-row">
                    {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link {% if request.path == url_for('posts.list_all') %}active{% endif %}"
                           href="{{ url_for('posts.list_all') }}">
                            Posts <span class="sr-only"></span>
                        </a>
                        {% if 'Admin' in current_user.role or 'Author' in current_user.role %}
                            <a class="nav-item nav-link"
                               href="{{ url_for('posts.list_author_posts') }}">
                                My Posts
                            </a>
                        {% endif %}
                        {% if 'Admin' in current_user.role %}
                            <a class="nav-item nav-link {% if request.path == url_for('users.list_all') %}active{% endif %}"
                               href="{{ url_for('users.list_all') }}">
                                Users
                            </a>
                        {% endif %}
                    {% endif %}
                </div>
                <div class="d-flex flex-row">
                    {% if not current_user.is_authenticated %}
                        <a class="nav-item nav-link {% if request.path == url_for('auth.login') %}active{% endif %}"
                           href="{{ url_for('auth.login') }}">
                            Login
                        </a>
                        <a class="nav-item nav-link {% if request.path == url_for('auth.signup') %}active{% endif %}"
                           href="{{ url_for('auth.signup') }}">
                            Signup
                        </a>
                    {% else %}
                        {% if 'Admin' in current_user.role or 'Author' in current_user.role %}
                            <a class="btn btn-primary ml-3 mt-auto mb-auto" href="{{ url_for("posts.create") }}">
                                Create Post
                            </a>
                        {% endif %}
                        <a class="btn btn-danger ml-3 mt-auto mb-auto" href="{{ url_for("auth.logout") }}">
                            Logout
                        </a>
                    {% endif %}
                </div>
            </div>
        </div>
    </header>
{% endblock %}

{% block content %}
    <div class="app container mt-5">
        {% block container %}
        {% endblock %}
    </div>
{% endblock %}